---
boost:
  target:
    entity:
      integration: heatzy
      domain: climate
  fields:
    delay:
      required: true
      selector:
        number:
          mode: slider
          unit_of_measurement: "minutes"
          min: 1
          max: 255

vacation:
  target:
    entity:
      integration: heatzy
      domain: climate
  fields:
    delay:
      required: true
      selector:
        number:
          mode: slider
          unit_of_measurement: "days"
          min: 1
          max: 255
          translation_key: "vacation_mode"

presence:
  target:
    entity:
      integration: heatzy
      domain: climate
