---
boost:
  target:
    entity:
      integration: heatzy
      domain: climate
  fields:
    delay:
      required: true
      selector:
        select:
          translation_key: "boost_mode"
          mode: dropdown
          options:
            - None
            - "30"
            - "60"
            - "90"
            - "120"

vacation:
  target:
    entity:
      integration: heatzy
      domain: climate
  fields:
    delay:
      required: true
      selector:
        number:
          mode: slider
          unit_of_measurement: "days"
          translation_key: delay
          min: 0
          max: 30

presence:
  target:
    entity:
      integration: heatzy
      domain: climate
  fields:
    enabled:
      required: true
      selector:
        boolean:
