---
boost:
  description: Start a boost
  target:
    entity:
      integration: heatzy
      domain: climate
  fields:
    delay:
      required: true
      name: Delay
      description: Boost delay (minutes)
      selector:
        select:
          mode: dropdown
          options:
            - 30
            - 60
            - 90
            - 120

vacation:
  description: Start a vacation
  target:
    entity:
      integration: heatzy
      domain: climate
  fields:
    delay:
      required: true
      name: Vacation
      description: Vacation delay (days)
      selector:
        number:
          mode: slider
          unit_of_measurement: "days"
          min: 1
          max: 30

presence:
  description: Presence detection
  target:
    entity:
      integration: heatzy
      domain: climate
